### ISSUE TITLE
Can I feed in a rubix cube state and get out some moves to solve it?

### ISSUE THREAD

**Issue by Anonymous3-a** [kongaskristjan/rubik#2]
Eg, if I had an unsolved cube, and I feed in the state, and it outputs the moves to solve it.

**Comment by kongaskristjan** [comment]
Sorry for the long wait.

Unfortunately it right now does not support this. The logic is mostly centered around scrambling solved cubes and then solving them. If you want to modify the code to be able to do this, I suggest passing the initial state string to `slow = slowCube.Cube(s)`. You also need to modify RubikEnv to accept this cube, as right now it only supports scrambling an already solved cube. main.py:testSolve() also needs to be modified.

Overall not a trivial task but should be doable should you really need it/want it.

**Comment by kongaskristjan** [comment]
About slow/fast cubes. SlowCube is an open source rubik's cube simulator that I found and copied into the project. It however turned out to be too slow for the training. To improve speed, I recorded the way slowcube changes with each move, and created a mapping. This allows me to execute a move with a single numpy remap, which is extremely fast.

For you, speed probably doesn't matter.

**Comment by Anonymous3-a** [comment]
Alright, thanks. I don't really need/want it *that* bad, but I might do it sometime. If I do, I'll see about making a PR to add a flag to input a state and have it solve that.  
Also, you're right, speed doesn't really matter for me.
